<?php 

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

function theme_enqueue_styles() {
    wp_enqueue_style( 'main-css', get_stylesheet_directory_uri() . '/styles/main.css' );
}

add_action( 'wp_enqueue_scripts', 'theme_js_child' );
function theme_js_child() {
	// wp_enqueue_script( 'jquery', get_stylesheet_directory_uri() . 'js/min/jquery.min-min.js', array( 'jquery' ), '1.0', true );
    wp_enqueue_script( 'scripts-main', get_stylesheet_directory_uri() . '/scripts/min/main-min.js', array(), false, true );
    
}

add_theme_support( 'menus' );
add_theme_support( 'post-thumbnails' );

function wpse27856_set_content_type(){
    return "text/html";
}
add_filter( 'wp_mail_content_type','wpse27856_set_content_type' );

function form_template($form_data){
$html = '';

if(!$form_data){
	return $html;
}

$html .= '<table style="border: 1px solid #e0e0e0; width: 50%; margin: auto;">';
	$html .= '<tr>';
  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">personal information</th>';
  	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Full Name</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["full-name"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Image</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;"></td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Address</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["address"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Age</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["age"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Gender</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["gender"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Date of Birth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["date-birth"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Place of Birth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["place-birth"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Nationality</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["nationality"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Civil Status</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["civil-status"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Religion</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["religion"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Contact Number</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["contact-number"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Blood Type</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["blood-type"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Height (cm)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["height"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Weight (kg)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["weight"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Waist (cm)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["waist"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Coat Size</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["coat-size"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Shoe Size</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["shoe-size"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">SSS</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["sss"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Philhealth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["philhealth"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Tax ID Number</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["tax-id"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Pag-ibig</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["pag-ibig"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Next of Kin</th>';
  	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Next of Kin (full name)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["next-kin"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Relation</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["relation"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Address</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["kin-address"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Contact Number</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["kin-number"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Dependents</th>';
  	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Dependent 1 (full name)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-1"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Date of Birth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-birth-1"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Dependent 2 (full name)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-2"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Date of Birth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-birth-2"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Dependent 3 (full name)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-3"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Date of Birth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-birth-3"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Dependent 4 (full name)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-4"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Date of Birth</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["dependent-birth-4"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Educational Background</th>';
  	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">School</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["school"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Course</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["course"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Year Graduated</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["yr-graduated"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">English Proficiency</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["eng-prof"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Employment</th>';
  	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">ID Number</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["id-number"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Rank</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["rank"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Vessel</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["vessel"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Total Sea Service</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["sea-service"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Seatime (Pres.Rank)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["seatime"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Years with Company</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["yrs-company"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Years with GLOCAL/Kambara</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["yrs-glocal"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Documents, Licenses, & Certificates</th>';
  	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Passport Number</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["passport-number"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Issued</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["passport-issued"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Expiry</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["passport-expiry"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Sbook (PH)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["sbook"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Issued</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["sbook-issued"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">SRC</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["src"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Issued</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["src-issued"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">License (PH)</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["license"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Issued</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["license-issued"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">US Visa</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["us-visa"].'</td>';
	$html .= '</tr>';
	$html .= '<tr>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Expiry</td>';
		$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["us-expiry"].'</td>';
	$html .= '</tr>';

	$docs_name_count = count($form_data["docs-name"]);
	if($docs_name_count){
		$html .= '<tr>';
	  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Documents, Licenses, & Certificates</th>';
	  	$html .= '</tr>';
		for ($i=0; $i < $docs_name_count; $i++) :
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Document Name</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["docs-name"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Document Number</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["docs-number"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Req\'d 4</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["docs-reqd"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Grade</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.(isset($form_data["docs-grade"][$i]) ? $form_data["docs-grade"][$i] : "N/A" ).'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Expiry</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.(isset($form_data["docs-expiry"][$i]) ? $form_data["docs-expiry"][$i] : "N/A").'</td>';
			$html .= '</tr>';
		endfor;
	}

	$history_name_count = count($form_data["history-name"]);
	if($history_name_count){
		$html .= '<tr>';
	  	$html .= '<th colspan="2" style="border: 1px solid #e0e0e0; padding: 10px; text-transform: uppercase;">Service History</th>';
	  	$html .= '</tr>';
		for ($i=0; $i < $history_name_count; $i++) :
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Company Name</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-name"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Rank</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-rank"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Embark</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-embark"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Disembark</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-disembark"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Vessel Name</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-vessel"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Type</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-type"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">GT</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-gt"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Engine</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-engine"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">HP</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-hp"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">Reason</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-reason"][$i].'</td>';
			$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">FR</td>';
				$html .= '<td style="border: 1px solid #e0e0e0; padding: 8px;">'.$form_data["history-fr"][$i].'</td>';
			$html .= '</tr>';
		endfor;
	}
$html .= '</table>';

return $html;
}